name: flutter_starter_template
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ^3.24.0

dependencies:
  analytics_core:
    path: ./packages/analytics_core
  auth_core:
    path: ./packages/auth_core
  collection: ^1.18.0
  copy_with_extension: ^5.0.4
  data_privacy:
    path: ./packages/data_privacy
  device_info_plus: ^10.1.0
  dynamic_color: ^1.7.0
  error_logging_core:
    path: ./packages/error_logging_core
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_displaymode: ^0.6.0
  flutter_dotenv: ^5.1.0
  flutter_gen: any
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.1.0
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.3.0
  package_info_plus: ^8.0.0
  pub_semver: ^2.1.4
  purchases_core:
    path: ./packages/purchases_core
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  toastification: ^2.1.0
  url_strategy: ^0.2.0
  vibration: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.12
  copy_with_extension_gen: ^5.0.4
  custom_lint: ^0.6.5
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - env/
    - assets/images/
    - assets/icons/
    - assets/fonts/
