name: challenge_entries
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  dart_appwrite: ^12.1.0
  http: ^1.0.0
  instagram_models:
    git:
      url: https://github.com/Zambrella/instagram-challenge-manager.git
      path: instagram_models

dev_dependencies:
  lints: ^4.0.0
