name: purchases_core
description: Abstract interface and models for in app purchases and subscriptions
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.2
  very_good_analysis: ^6.0.0
